/**
 * DICT Key Bulk Creator (createEntry / deleteEntry).
 *
 * Creates many entries (key -> account -> owner) in the DICT, e.g. to prepare
 * DICT functionality and capacity tests, and deletes them afterwards.
 *
 * DICT API v2.12.1 (simulator/spec/dict-2.12.1/openapi.json):
 *   createEntry  POST /entries/               body <CreateEntryRequest>   201 Created
 *   deleteEntry  POST /entries/{Key}/delete   body <DeleteEntryRequest>   200 OK
 *   (DELETE is not used; the removal is a POST to .../delete.)
 *
 * CreateEntryRequest: Signature, Entry{Key, KeyType, Account, Owner}, Reason, RequestId
 *   - Reason: USER_REQUESTED or RECONCILIATION.
 *   - RequestId: UUID v4, idempotency key, unique per participant. It is also
 *     used in the entry's CID. Reusing it with different data -> RequestIdAlreadyUsed.
 *   - EVP keys are generated by the DICT: send KeyType=EVP without <Key>
 *     (Entry.Key is optional in the schema); the key comes back in the response.
 *   - Account.OpeningDate is required; if the time is unknown use the start of
 *     the day in BRT (03:00Z). Branch is optional (1-4 digits, no check digit).
 * DeleteEntryRequest: Signature, Key, Participant, Reason
 *   - Reason: USER_REQUESTED, ACCOUNT_CLOSURE, RECONCILIATION, FRAUD or RFB_VALIDATION.
 * Rate limit: ENTRIES_WRITE (createEntry + deleteEntry) 1200/min, bucket 36000 per PSP.
 *
 * SIGNATURE: every write must carry an enveloped XMLDSig in <Signature>
 * (Manual de Seguranca do Pix). The XML built here leaves <Signature></Signature>
 * empty; it MUST be signed before sending or the DICT refuses it.
 *
 * Per-account key limits (commonly 5 per account for natural persons and 20
 * for legal persons) are set by the Pix regulation, not by the API spec;
 * verify them against the current Regulamento Pix before relying on them.
 *
 * Usage:
 *   npx tsx scripts/dict/key-bulk-creator.ts [keyType] [count]
 *   npx tsx scripts/dict/key-bulk-creator.ts EVP 1000
 *   npx tsx scripts/dict/key-bulk-creator.ts delete <key> [reason]
 */

import { DictClient } from "../utils/http-client.js";
import {
  generateNaturalPerson,
  generateLegalPerson,
  generateBankAccount,
  generateDictKey,
} from "../utils/test-data-generator.js";
import {
  type BrazilianAccount,
  type KeyType,
  type Person,
  DictValidationError,
  SIGNATURE_WARNING,
  accountNodes,
  assertEnum,
  assertKey,
  assertKeyType,
  assertParticipant,
  assertUuid,
  describeDictError,
  detectKeyType,
  dictClientFromEnv,
  dictDocument,
  installCliErrorHandler,
  missingEnv,
  newRequestId,
  parseDictXml,
  personNodes,
  startOfDayBrt,
  validateAccount,
  validatePerson,
} from "./key-lookup.js";

export const CREATE_ENTRY_REASONS = ["USER_REQUESTED", "RECONCILIATION"] as const;
export type CreateEntryReason = (typeof CREATE_ENTRY_REASONS)[number];

export const DELETE_ENTRY_REASONS = [
  "USER_REQUESTED",
  "ACCOUNT_CLOSURE",
  "RECONCILIATION",
  "FRAUD",
  "RFB_VALIDATION",
] as const;
export type DeleteEntryReason = (typeof DELETE_ENTRY_REASONS)[number];

export interface CreateEntryParams {
  keyType: KeyType;
  /** Omit for EVP (generated by the DICT). Required for the other types. */
  key?: string;
  account: BrazilianAccount;
  owner: Person;
  reason?: CreateEntryReason;
  /** UUID v4; generated when omitted. Keep it to retry idempotently. */
  requestId?: string;
}

export interface DeleteEntryParams {
  key: string;
  /** ISPB of the participant that holds the entry (the requester). */
  participant: string;
  reason: DeleteEntryReason;
}

export function buildCreateEntryRequest(params: CreateEntryParams): string {
  const keyType = assertKeyType(params.keyType);
  if (keyType === "EVP") {
    if (params.key !== undefined) {
      throw new DictValidationError("EVP keys are generated by the DICT: omit Key in createEntry");
    }
  } else {
    assertKey(keyType, params.key);
  }
  validateAccount(params.account, "Entry.Account");
  validatePerson(params.owner, "Entry.Owner");
  const reason = assertEnum(params.reason ?? "USER_REQUESTED", CREATE_ENTRY_REASONS, "Reason");
  const requestId = assertUuid(params.requestId ?? newRequestId(), "RequestId");

  return dictDocument("CreateEntryRequest", [
    ["Entry", [
      ["Key", params.key],
      ["KeyType", keyType],
      ["Account", accountNodes(params.account)],
      ["Owner", personNodes(params.owner)],
    ]],
    ["Reason", reason],
    ["RequestId", requestId],
  ]);
}

export function buildDeleteEntryRequest(params: DeleteEntryParams): string {
  const keyType = detectKeyType(params.key);
  if (!keyType) throw new DictValidationError(`Key has no known format: ${JSON.stringify(params.key)}`);
  assertKey(keyType, params.key);
  assertParticipant(params.participant);
  assertEnum(params.reason, DELETE_ENTRY_REASONS, "Reason");

  return dictDocument("DeleteEntryRequest", [
    ["Key", params.key],
    ["Participant", params.participant],
    ["Reason", params.reason],
  ]);
}

/** POST /entries/ — returns the created key (the DICT-generated one for EVP). */
export async function createEntry(client: DictClient, params: CreateEntryParams): Promise<string> {
  const res = await client.call("POST", "/entries/", buildCreateEntryRequest(params));
  return parseDictXml(res.body).CreateEntryResponse?.Entry?.Key ?? params.key ?? "";
}

/** POST /entries/{Key}/delete */
export async function deleteEntry(client: DictClient, params: DeleteEntryParams): Promise<void> {
  await client.call("POST", `/entries/${encodeURIComponent(params.key)}/delete`, buildDeleteEntryRequest(params));
}

/** Random entry of the given type, with key and owner consistent for CPF/CNPJ. */
export function randomEntryParams(ispb: string, keyType: KeyType): CreateEntryParams {
  const holder = keyType === "CNPJ" ? generateLegalPerson()
    : keyType === "CPF" ? generateNaturalPerson()
    : Math.random() > 0.3 ? generateNaturalPerson() : generateLegalPerson();
  const account = generateBankAccount(ispb, holder);

  return {
    keyType,
    key: keyType === "EVP" ? undefined : generateDictKey(keyType, account).value,
    account: {
      participant: ispb,
      branch: account.branch,
      accountNumber: account.accountNumber,
      accountType: account.accountType,
      openingDate: startOfDayBrt(),
    },
    owner: { type: holder.type, taxIdNumber: holder.document, name: holder.name },
    reason: "USER_REQUESTED",
    requestId: newRequestId(),
  };
}

interface BulkCreateResult {
  total: number;
  created: number;
  failed: number;
  keys: string[];
  errors: Array<{ key: string; error: string }>;
}

export async function bulkCreateKeys(
  client: DictClient,
  ispb: string,
  keyType: KeyType,
  count: number,
  concurrency = 10,
): Promise<BulkCreateResult> {
  const result: BulkCreateResult = { total: count, created: 0, failed: 0, keys: [], errors: [] };
  const entries = Array.from({ length: count }, () => randomEntryParams(ispb, keyType));

  for (let i = 0; i < entries.length; i += concurrency) {
    const batch = entries.slice(i, i + concurrency);
    await Promise.all(batch.map(async (params) => {
      try {
        result.keys.push(await createEntry(client, params));
        result.created++;
      } catch (err) {
        result.failed++;
        result.errors.push({ key: params.key ?? `EVP (RequestId ${params.requestId})`, error: describeDictError(err) });
      }
    }));

    const done = Math.min(i + concurrency, entries.length);
    if (done % 100 === 0 || done === entries.length) {
      console.log(`  Progress: ${done}/${count} (created: ${result.created}, failed: ${result.failed})`);
    }
  }

  return result;
}

// CLI usage
if (import.meta.url === `file://${process.argv[1]}`) {
  installCliErrorHandler();
  const ispb = process.env.PSP_ISPB || "12345678";
  const missing = missingEnv();

  console.log(`=== DICT Key Bulk Creator ===`);
  console.log(`${SIGNATURE_WARNING}\n`);

  if (process.argv[2] === "delete") {
    const key = process.argv[3] || "+5561988887777";
    const reason = (process.argv[4] || "USER_REQUESTED") as DeleteEntryReason;
    const xml = buildDeleteEntryRequest({ key, participant: ispb, reason });

    if (missing.length > 0) {
      console.error(`Missing environment variables: ${missing.join(", ")}\n`);
      console.log(`--- Demo Mode: POST /api/v2/entries/${encodeURIComponent(key)}/delete ---\n`);
      console.log(xml);
      process.exit(0);
    }

    const client = dictClientFromEnv();
    deleteEntry(client, { key, participant: ispb, reason })
      .then(() => console.log(`Deleted: ${key}`))
      .catch((err) => {
        console.error("Delete failed:", describeDictError(err));
        process.exitCode = 1;
      })
      .finally(() => client.destroy());
  } else {
    const keyType = assertKeyType(process.argv[2] || "EVP");
    const count = parseInt(process.argv[3] || "10", 10);
    console.log(`Key type: ${keyType}, Count: ${count}\n`);

    if (missing.length > 0) {
      console.error(`Missing environment variables: ${missing.join(", ")}`);
      console.error("Copy config/homolog.env.example to .env and configure.\n");
      console.log("--- Demo Mode: POST /api/v2/entries/ ---\n");
      console.log(buildCreateEntryRequest(randomEntryParams(ispb, keyType)));
      process.exit(0);
    }

    const client = dictClientFromEnv();
    bulkCreateKeys(client, ispb, keyType, count)
      .then((result) => {
        console.log("\n=== Results ===");
        console.log(`Total:   ${result.total}`);
        console.log(`Created: ${result.created}`);
        console.log(`Failed:  ${result.failed}`);
        if (result.errors.length > 0) {
          console.log("\nFirst 10 errors:");
          result.errors.slice(0, 10).forEach((e) => console.log(`  ${e.key}: ${e.error}`));
        }
      })
      .catch((err) => {
        console.error("Bulk create failed:", describeDictError(err));
        process.exitCode = 1;
      })
      .finally(() => client.destroy());
  }
}
